<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class G8GameListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [

            [
                "game_id" => "1",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Commision Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "2",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Commision Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "3",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Commision Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "30",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Commision Baccarat 4",
                "image" => "",
            ],
            [
                "game_id" => "31",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "No Commision Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "32",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "No Commision Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "33",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "No Commision Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "40",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "No Commision Baccarat 4",
                "image" => "",
            ],
            [
                "game_id" => "24",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Tiger Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "26",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Tiger Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "27",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Tiger Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "34",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Tiger Baccarat 4",
                "image" => "",
            ],
            [
                "game_id" => "113",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super 98 Baccarat",
                "image" => "",
            ],
            [
                "game_id" => "223",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Fabulous 4 Baccarat",
                "image" => "",
            ],
            [
                "game_id" => "18",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => " Lucky Baccarat",
                "image" => "",
            ],
            [
                "game_id" => "23",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => " Baccarat Insurance (Commission)",
                "image" => "",
            ],
            [
                "game_id" => "22",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => " Baccarat Insurance (No Commission)",
                "image" => "",
            ],
            [
                "game_id" => "4",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Dragon Tiger 1",
                "image" => "",
            ],
            [
                "game_id" => "14",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Dragon Tiger 2",
                "image" => "",
            ],
            [
                "game_id" => "5",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Sicbo 1",
                "image" => "",
            ],
            [
                "game_id" => "15",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Sicbo 2",
                "image" => "",
            ],
            [
                "game_id" => "35",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Sicbo 1",
                "image" => "",
            ],
            [
                "game_id" => "39",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Sicbo 1",
                "image" => "",
            ],
            [
                "game_id" => "45",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Thai Hi-Lo 1",
                "image" => "",
            ],
            [
                "game_id" => "49",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Thai Hi-Lo 2",
                "image" => "",
            ],
            [
                "game_id" => "29",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Xoc Dia",
                "image" => "",
            ],
            [
                "game_id" => "9",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Color Sicbo",
                "image" => "",
            ],
            [
                "game_id" => "6",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Roulette 1",
                "image" => "",
            ],
            [
                "game_id" => "16",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Roulette 2",
                "image" => "",
            ],
            [
                "game_id" => "36",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Roulette 1",
                "image" => "",
            ],
            [
                "game_id" => "46",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Roulette 2",
                "image" => "",
            ],
            [
                "game_id" => "38",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super 3 Pictures",
                "image" => "",
            ],
            [
                "game_id" => "10",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Blackjack",
                "image" => "",
            ],
            [
                "game_id" => "42",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Super Fantan",
                "image" => "",
            ],
            [
                "game_id" => "1001",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Commision Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "1002",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Commision Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "1031",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual No Commision Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "1032",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual No Commision Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "1061",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual C Squeeze Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "1062  ",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual C Squeeze Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "1091",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual NC Squeeze Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "1092",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual NC Squeeze Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "1018",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Lucky Baccarat 1",
                "image" => "",
            ],
            [
                "game_id" => "1028",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Lucky Baccarat 2",
                "image" => "",
            ],
            [
                "game_id" => "1004",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Dragon Tiger 1",
                "image" => "",
            ],
            [
                "game_id" => "1014",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Dragon Tiger 2",
                "image" => "",
            ],
            [
                "game_id" => "1005",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Sicbo",
                "image" => "",
            ],
            [
                "game_id" => "1006",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Roulette",
                "image" => "",
            ],
            [
                "game_id" => "1036",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Super Roulette",
                "image" => "",
            ],
            [
                "game_id" => "1035",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Super Sicbo",
                "image" => "",
            ],
            [
                "game_id" => "1017",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Super Hi-Lo",
                "image" => "",
            ],
            [
                "game_id" => "1007",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual 7 Up Baccarat",
                "image" => "",
            ],
            [
                "game_id" => "1045",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Thai Hi-Lo",
                "image" => "",
            ],
            [
                "game_id" => "1023",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Fabulous 4 Baccarat",
                "image" => "",
            ],
            [
                "game_id" => "1070",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Three Card Poker",
                "image" => "",
            ],
            [
                "game_id" => "1003",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual Commision Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "1033",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual No Commision Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "1063",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual C Squeeze Baccarat 3",
                "image" => "",
            ],
            [
                "game_id" => "1093",
                "provider_id" =>  3,
                "game_type_id" => 2,
                "name_en" => "Virtual NC Squeeze Baccarat 3",
                "image" => "",
            ],
        ];
        foreach ($data as $value) {

            GameList::create([
                'game_id' => $value['game_id'],
                'provider_id' => $value['provider_id'],
                'game_type_id' => $value['game_type_id'],
                'name_en' => $value['name_en'],
                'image' => $value['image']
            ]);
        }
    }
}
